/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';

declare let self: ServiceWorkerGlobalScope;

// Cache versioning to force PWA refresh
const SW_VERSION = 'v42-mobile-pwa-auto-update';
console.log(`[SW] Initializing Service Worker ${SW_VERSION}`);

// Take control of all clients as soon as the service worker activates
clientsClaim();

// Automatically cleanup old caches provided by workbox
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Removed automatic skipWaiting to restore the "Update App" prompt

// Also keep the message listener just in case
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Fallback for navigation requests (SPA routing)
// If the user navigates to a new URL, serve the precached index.html
registerRoute(
  new NavigationRoute(async ({ request }) => {
    try {
      // Try to fetch from network first for the freshest index.html if possible
      const response = await fetch(request);
      return response;
    } catch (error) {
      // If offline or network fails, fallback to precached index.html
      const cache = await caches.match('/index.html');
      return cache || Response.error();
    }
  })
);

self.addEventListener('pushsubscriptionchange', () => {
  // Token refresh is handled when the app next requests FCM permission.
});

// Firebase Cloud Messaging background message handler
self.addEventListener('push', (event) => {
  console.log('[SW] Push message received:', event);

  if (!event.data) return;

  let payload: any = {};
  try {
    payload = event.data.json();
  } catch (error) {
    payload = { title: 'BhojanOS', body: event.data.text() };
  }

  const notification = payload.notification || payload;
  const data = payload.data || {};
  console.log('[SW] Push notification data:', payload);

  const options = {
    body: notification.body || data.body || 'New notification from BhojanOS',
    icon: notification.icon || '/icon-v20-192.png',
    badge: '/icon-v20-192.png',
    vibrate: [200, 100, 200, 100, 200],
    silent: false,
    data,
    requireInteraction: true,
    actions: [
      {
        action: 'view',
        title: 'View Order'
      }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(notification.title || data.title || 'BhojanOS', options)
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification click received:', event);

  event.notification.close();

  const data = event.notification.data || {};
  const orderId = data.orderId;
  const url = data.url || (orderId ? `/order/${orderId}` : '/my-orders');

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window is already open, focus it and navigate
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(url);
          return client.focus();
        }
      }
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(url);
      }
    })
  );
});
