/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, NetworkOnly, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

// Cache versioning to force PWA refresh
const SW_VERSION = 'v46-auth-network-only';
console.log(`[SW] Initializing Service Worker ${SW_VERSION}`);

// Take control of all clients as soon as the service worker activates
clientsClaim();

// Automatically cleanup old caches provided by workbox
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Never let the SW touch Firebase Auth / token endpoints (stale SW → auth/network-request-failed).
registerRoute(
  ({ url }) => {
    const host = url.hostname;
    if (host === 'identitytoolkit.googleapis.com' || host === 'securetoken.googleapis.com') {
      return true;
    }
    if (host === 'www.googleapis.com' || host.endsWith('.googleapis.com')) {
      return (
        url.pathname.includes('/identitytoolkit/') ||
        url.pathname.includes('/securetoken/') ||
        url.pathname.includes('/relyingparty/')
      );
    }
    return false;
  },
  new NetworkOnly(),
);

registerRoute(
  ({ request }) => request.destination === 'image' || request.destination === 'font',
  new CacheFirst({
    cacheName: 'bds-static-media',
    plugins: [new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  }),
);

registerRoute(
  ({ url, request }) =>
    request.method === 'GET' &&
    url.pathname === '/version.json' &&
    !url.pathname.startsWith('/api/'),
  new StaleWhileRevalidate({
    cacheName: 'bds-public-json',
    plugins: [new ExpirationPlugin({ maxEntries: 8, maxAgeSeconds: 60 * 10 })],
  }),
);

registerRoute(
  ({ url, request }) =>
    url.pathname.startsWith('/api/create-razorpay-order') ||
    url.pathname.startsWith('/api/verify-razorpay-payment') ||
    url.pathname.startsWith('/api/auth') ||
    url.pathname.startsWith('/api/owner/') ||
    url.pathname.includes('/checkout') ||
    url.pathname.includes('/payment'),
  new NetworkOnly(),
);

registerRoute(
  ({ url, request }) =>
    request.method === 'GET' &&
    /\/api\/marketplace\/restaurants\/[^/]+\/menu(?:\/|$)/.test(url.pathname) &&
    !url.pathname.includes('auth') &&
    !url.pathname.includes('payment') &&
    !url.pathname.includes('order'),
  new StaleWhileRevalidate({
    cacheName: 'bds-marketplace-menu',
    plugins: [new ExpirationPlugin({ maxEntries: 32, maxAgeSeconds: 60 * 10 })],
  }),
);

// Removed automatic skipWaiting to restore the "Update App" prompt

// Also keep the message listener just in case
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Fallback for navigation requests (SPA routing).
// Vercel renames the app shell to app.html; Capacitor/Firebase keep index.html.
registerRoute(
  new NavigationRoute(async ({ request }) => {
    try {
      const response = await fetch(request);
      return response;
    } catch {
      const url = new URL(request.url);
      const marketingPath =
        url.pathname === '/' ||
        /\/(onboard|pricing|about|platform|security|contact|blog)\/?$/.test(url.pathname);
      const candidates = marketingPath
        ? ['/marketing.html', '/index.html', '/app.html']
        : ['/app.html', '/index.html', '/marketing.html'];
      for (const path of candidates) {
        const cached = await caches.match(path);
        if (cached) return cached;
      }
      return Response.error();
    }
  })
);

self.addEventListener('pushsubscriptionchange', () => {
  // Token refresh is handled when the app next requests FCM permission.
});

// Firebase Cloud Messaging background message handler
self.addEventListener('push', (event) => {
  console.log('[SW] Push message received:', event);

  if (!event.data) return;

  let payload: any = {};
  try {
    payload = event.data.json();
  } catch (error) {
    payload = { title: 'BhojanOS', body: event.data.text() };
  }

  const notification = payload.notification || payload;
  const data = payload.data || {};
  console.log('[SW] Push notification data:', payload);

  const options = {
    body: notification.body || data.body || 'New notification from BhojanOS',
    icon: notification.icon || '/icon-v20-192.png',
    badge: '/icon-v20-192.png',
    vibrate: [200, 100, 200, 100, 200],
    silent: false,
    data,
    requireInteraction: true,
    actions: [
      {
        action: 'view',
        title: 'View Order'
      }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(notification.title || data.title || 'BhojanOS', options)
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification click received:', event);

  event.notification.close();

  const data = event.notification.data || {};
  const orderId = data.orderId;
  const url = data.url || (orderId ? `/order/${orderId}` : '/my-orders');

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window is already open, focus it and navigate
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(url);
          return client.focus();
        }
      }
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(url);
      }
    })
  );
});
