/**
 * PricingSDK feature flags (M8 PR-1).
 * All flags default OFF — zero production impact.
 */

export type PricingSdkFeatureFlag =
  | 'FF_PRICING_ENABLED'
  | 'FF_DYNAMIC_PRICING_ENABLED'
  | 'FF_COUPONS_ENABLED'
  | 'FF_OFFERS_ENABLED'
  | 'FF_PRICING_PROJECTION_ENABLED'
  | 'FF_PRICING_PROJECTION_PARITY_ENABLED'
  | 'FF_PRICING_PROJECTION_SOAK_ENABLED'
  | 'FF_PRICING_OPERATIONAL_VALIDATION_ENABLED';

export const PRICING_SDK_FEATURE_FLAG_DEFAULTS = {
  flags: {
    FF_PRICING_ENABLED: false,
    FF_DYNAMIC_PRICING_ENABLED: false,
    FF_COUPONS_ENABLED: false,
    FF_OFFERS_ENABLED: false,
    FF_PRICING_PROJECTION_ENABLED: false,
    FF_PRICING_PROJECTION_PARITY_ENABLED: false,
    FF_PRICING_PROJECTION_SOAK_ENABLED: false,
    FF_PRICING_OPERATIONAL_VALIDATION_ENABLED: false,
  },
} as const;

export const PRICING_SDK_FEATURE_FLAG_ENV_KEYS: Record<PricingSdkFeatureFlag, string> = {
  FF_PRICING_ENABLED: 'VITE_FF_PRICING_ENABLED',
  FF_DYNAMIC_PRICING_ENABLED: 'VITE_FF_DYNAMIC_PRICING_ENABLED',
  FF_COUPONS_ENABLED: 'VITE_FF_COUPONS_ENABLED',
  FF_OFFERS_ENABLED: 'VITE_FF_OFFERS_ENABLED',
  FF_PRICING_PROJECTION_ENABLED: 'VITE_FF_PRICING_PROJECTION_ENABLED',
  FF_PRICING_PROJECTION_PARITY_ENABLED: 'VITE_FF_PRICING_PROJECTION_PARITY_ENABLED',
  FF_PRICING_PROJECTION_SOAK_ENABLED: 'VITE_FF_PRICING_PROJECTION_SOAK_ENABLED',
  FF_PRICING_OPERATIONAL_VALIDATION_ENABLED: 'VITE_FF_PRICING_OPERATIONAL_VALIDATION_ENABLED',
};

export type PricingFeatureFlagReader = (flag: PricingSdkFeatureFlag) => boolean;

export const readPricingFlagDefault = (flag: PricingSdkFeatureFlag): boolean =>
  PRICING_SDK_FEATURE_FLAG_DEFAULTS.flags[flag];
