/**
 * EventSDK feature flags (M6 PR-4).
 * All flags default OFF — zero production impact.
 */

export type EventSdkFeatureFlag =
  | 'FF_EVENT_PLATFORM_ENABLED'
  | 'FF_EVENT_OUTBOX_ENABLED'
  | 'FF_EVENT_REPLAY_ENABLED'
  | 'FF_EVENT_SHADOW_PUBLISHING_ENABLED'
  | 'FF_EVENT_PROJECTION_ENABLED'
  | 'FF_ORDER_SHADOW_EVENTS_ENABLED'
  | 'FF_EVENT_PROJECTION_RUNTIME_ENABLED'
  | 'FF_ORDER_READ_PROJECTION_ENABLED'
  | 'FF_ORDER_PROJECTION_PARITY_ENABLED'
  | 'FF_ORDER_PROJECTION_SOAK_ENABLED'
  | 'FF_EVENT_OPERATIONAL_VALIDATION_ENABLED';

export const EVENT_SDK_FEATURE_FLAG_DEFAULTS = {
  flags: {
    FF_EVENT_PLATFORM_ENABLED: false,
    FF_EVENT_OUTBOX_ENABLED: false,
    FF_EVENT_REPLAY_ENABLED: false,
    FF_EVENT_SHADOW_PUBLISHING_ENABLED: false,
    FF_EVENT_PROJECTION_ENABLED: false,
    FF_ORDER_SHADOW_EVENTS_ENABLED: false,
    FF_EVENT_PROJECTION_RUNTIME_ENABLED: false,
    FF_ORDER_READ_PROJECTION_ENABLED: false,
    FF_ORDER_PROJECTION_PARITY_ENABLED: false,
    FF_ORDER_PROJECTION_SOAK_ENABLED: false,
    FF_EVENT_OPERATIONAL_VALIDATION_ENABLED: false,
  },
} as const;

export const EVENT_SDK_FEATURE_FLAG_ENV_KEYS: Record<EventSdkFeatureFlag, string> = {
  FF_EVENT_PLATFORM_ENABLED: 'VITE_FF_EVENT_PLATFORM_ENABLED',
  FF_EVENT_OUTBOX_ENABLED: 'VITE_FF_EVENT_OUTBOX_ENABLED',
  FF_EVENT_REPLAY_ENABLED: 'VITE_FF_EVENT_REPLAY_ENABLED',
  FF_EVENT_SHADOW_PUBLISHING_ENABLED: 'VITE_FF_EVENT_SHADOW_PUBLISHING_ENABLED',
  FF_EVENT_PROJECTION_ENABLED: 'VITE_FF_EVENT_PROJECTION_ENABLED',
  FF_ORDER_SHADOW_EVENTS_ENABLED: 'VITE_FF_ORDER_SHADOW_EVENTS_ENABLED',
  FF_EVENT_PROJECTION_RUNTIME_ENABLED: 'VITE_FF_EVENT_PROJECTION_RUNTIME_ENABLED',
  FF_ORDER_READ_PROJECTION_ENABLED: 'VITE_FF_ORDER_READ_PROJECTION_ENABLED',
  FF_ORDER_PROJECTION_PARITY_ENABLED: 'VITE_FF_ORDER_PROJECTION_PARITY_ENABLED',
  FF_ORDER_PROJECTION_SOAK_ENABLED: 'VITE_FF_ORDER_PROJECTION_SOAK_ENABLED',
  FF_EVENT_OPERATIONAL_VALIDATION_ENABLED: 'VITE_FF_EVENT_OPERATIONAL_VALIDATION_ENABLED',
};

export type EventFeatureFlagReader = (flag: EventSdkFeatureFlag) => boolean;

export const readEventFlagDefault = (flag: EventSdkFeatureFlag): boolean =>
  EVENT_SDK_FEATURE_FLAG_DEFAULTS.flags[flag];
