/**
 * Menu domain — reason codes (M7 PR-2).
 */

export const MENU_REASON_CODES = {
  EMPTY_NAME: 'EMPTY_NAME',
  EMPTY_CATALOG_ID: 'EMPTY_CATALOG_ID',
  EMPTY_TENANT_ID: 'EMPTY_TENANT_ID',
  EMPTY_CATEGORY_ID: 'EMPTY_CATEGORY_ID',
  EMPTY_ITEM_ID: 'EMPTY_ITEM_ID',
  EMPTY_MODIFIER_ID: 'EMPTY_MODIFIER_ID',
  EMPTY_GROUP_ID: 'EMPTY_GROUP_ID',
  EMPTY_COMBO_ID: 'EMPTY_COMBO_ID',
  INVALID_SORT_ORDER: 'INVALID_SORT_ORDER',
  INVALID_PRICE: 'INVALID_PRICE',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  DUPLICATE_CATEGORY_ID: 'DUPLICATE_CATEGORY_ID',
  DUPLICATE_ITEM_ID: 'DUPLICATE_ITEM_ID',
  DUPLICATE_MODIFIER_ID: 'DUPLICATE_MODIFIER_ID',
  ORPHAN_ITEM_REFERENCE: 'ORPHAN_ITEM_REFERENCE',
  INACTIVE_CATEGORY: 'INACTIVE_CATEGORY',
  INACTIVE_ITEM: 'INACTIVE_ITEM',
  INVALID_AVAILABILITY_STATE: 'INVALID_AVAILABILITY_STATE',
  INVALID_SELECTION_RANGE: 'INVALID_SELECTION_RANGE',
  REQUIRED_GROUP_EMPTY: 'REQUIRED_GROUP_EMPTY',
  SELECTION_BELOW_MINIMUM: 'SELECTION_BELOW_MINIMUM',
  SELECTION_ABOVE_MAXIMUM: 'SELECTION_ABOVE_MAXIMUM',
  DUPLICATE_MODIFIER_SELECTION: 'DUPLICATE_MODIFIER_SELECTION',
  COMBO_MISSING_REQUIRED_COMPONENT: 'COMBO_MISSING_REQUIRED_COMPONENT',
  COMBO_EMPTY_COMPONENTS: 'COMBO_EMPTY_COMPONENTS',
  COMBO_INVALID_QUANTITY: 'COMBO_INVALID_QUANTITY',
  CATALOG_EMPTY: 'CATALOG_EMPTY',
} as const;

export type MenuReasonCode = (typeof MENU_REASON_CODES)[keyof typeof MENU_REASON_CODES];

export const MENU_REASON_MESSAGES: Record<MenuReasonCode, string> = {
  EMPTY_NAME: 'Name cannot be empty',
  EMPTY_CATALOG_ID: 'Catalog ID is required',
  EMPTY_TENANT_ID: 'Tenant ID is required',
  EMPTY_CATEGORY_ID: 'Category ID is required',
  EMPTY_ITEM_ID: 'Item ID is required',
  EMPTY_MODIFIER_ID: 'Modifier ID is required',
  EMPTY_GROUP_ID: 'Modifier group ID is required',
  EMPTY_COMBO_ID: 'Combo ID is required',
  INVALID_SORT_ORDER: 'Sort order must be a non-negative integer',
  INVALID_PRICE: 'Price amount must be a non-negative finite number',
  INVALID_CURRENCY: 'Currency code is required',
  DUPLICATE_CATEGORY_ID: 'Duplicate category ID detected',
  DUPLICATE_ITEM_ID: 'Duplicate item ID detected',
  DUPLICATE_MODIFIER_ID: 'Duplicate modifier ID detected',
  ORPHAN_ITEM_REFERENCE: 'Category references an unknown item ID',
  INACTIVE_CATEGORY: 'Category is inactive',
  INACTIVE_ITEM: 'Menu item is inactive',
  INVALID_AVAILABILITY_STATE: 'Availability state is invalid',
  INVALID_SELECTION_RANGE: 'Modifier selection min/max range is invalid',
  REQUIRED_GROUP_EMPTY: 'Required modifier group has no active modifiers',
  SELECTION_BELOW_MINIMUM: 'Modifier selection count is below minimum',
  SELECTION_ABOVE_MAXIMUM: 'Modifier selection count exceeds maximum',
  DUPLICATE_MODIFIER_SELECTION: 'Duplicate modifier selection is not allowed',
  COMBO_MISSING_REQUIRED_COMPONENT: 'Combo is missing a required component',
  COMBO_EMPTY_COMPONENTS: 'Combo must have at least one component',
  COMBO_INVALID_QUANTITY: 'Combo component quantity must be positive',
  CATALOG_EMPTY: 'Catalog must contain at least one category or item',
};
