/**
 * BranchSDK feature flags (M5 PR-1 foundation).
 * All flags default OFF — zero production impact until PR-2+.
 */

export type BranchSdkFeatureFlag =
  | 'FF_BRANCH_ENABLED'
  | 'FF_BRANCH_REPOSITORY_ENABLED'
  | 'FF_BRANCH_ASSIGNMENT_ENABLED'
  | 'FF_BRANCH_DISCOVERY_ENABLED'
  | 'FF_BRANCH_OPERATIONS_REPOSITORY_ENABLED'
  | 'FF_BRANCH_OPERATIONS_SDK_ENABLED';

export const BRANCH_SDK_FEATURE_FLAG_DEFAULTS = {
  flags: {
    FF_BRANCH_ENABLED: false,
    FF_BRANCH_REPOSITORY_ENABLED: false,
    FF_BRANCH_ASSIGNMENT_ENABLED: false,
    FF_BRANCH_DISCOVERY_ENABLED: false,
    FF_BRANCH_OPERATIONS_REPOSITORY_ENABLED: false,
    FF_BRANCH_OPERATIONS_SDK_ENABLED: false,
  },
} as const;

export const BRANCH_SDK_FEATURE_FLAG_ENV_KEYS: Record<BranchSdkFeatureFlag, string> = {
  FF_BRANCH_ENABLED: 'VITE_FF_BRANCH_ENABLED',
  FF_BRANCH_REPOSITORY_ENABLED: 'VITE_FF_BRANCH_REPOSITORY_ENABLED',
  FF_BRANCH_ASSIGNMENT_ENABLED: 'VITE_FF_BRANCH_ASSIGNMENT_ENABLED',
  FF_BRANCH_DISCOVERY_ENABLED: 'VITE_FF_BRANCH_DISCOVERY_ENABLED',
  FF_BRANCH_OPERATIONS_REPOSITORY_ENABLED: 'VITE_FF_BRANCH_OPERATIONS_REPOSITORY_ENABLED',
  FF_BRANCH_OPERATIONS_SDK_ENABLED: 'VITE_FF_BRANCH_OPERATIONS_SDK_ENABLED',
};

export type BranchFeatureFlagReader = (flag: BranchSdkFeatureFlag) => boolean;

export const readBranchFlagDefault = (flag: BranchSdkFeatureFlag): boolean =>
  BRANCH_SDK_FEATURE_FLAG_DEFAULTS.flags[flag];
