/**
 * MenuSDK feature flags (M7 PR-1).
 */

export type MenuSdkFeatureFlag =
  | 'FF_MENU_ENABLED'
  | 'FF_MENU_SEARCH_ENABLED'
  | 'FF_MENU_PROJECTION_ENABLED'
  | 'FF_MENU_PROJECTION_PARITY_ENABLED'
  | 'FF_MENU_PROJECTION_SOAK_ENABLED'
  | 'FF_MENU_OPERATIONAL_VALIDATION_ENABLED';

export const MENU_SDK_FEATURE_FLAG_DEFAULTS = {
  flags: {
    FF_MENU_ENABLED: false,
    FF_MENU_SEARCH_ENABLED: false,
    FF_MENU_PROJECTION_ENABLED: false,
    FF_MENU_PROJECTION_PARITY_ENABLED: false,
    FF_MENU_PROJECTION_SOAK_ENABLED: false,
    FF_MENU_OPERATIONAL_VALIDATION_ENABLED: false,
  },
} as const;

export const MENU_SDK_FEATURE_FLAG_ENV_KEYS: Record<MenuSdkFeatureFlag, string> = {
  FF_MENU_ENABLED: 'VITE_FF_MENU_ENABLED',
  FF_MENU_SEARCH_ENABLED: 'VITE_FF_MENU_SEARCH_ENABLED',
  FF_MENU_PROJECTION_ENABLED: 'VITE_FF_MENU_PROJECTION_ENABLED',
  FF_MENU_PROJECTION_PARITY_ENABLED: 'VITE_FF_MENU_PROJECTION_PARITY_ENABLED',
  FF_MENU_PROJECTION_SOAK_ENABLED: 'VITE_FF_MENU_PROJECTION_SOAK_ENABLED',
  FF_MENU_OPERATIONAL_VALIDATION_ENABLED: 'VITE_FF_MENU_OPERATIONAL_VALIDATION_ENABLED',
};

export type MenuFeatureFlagReader = (flag: MenuSdkFeatureFlag) => boolean;

export const readMenuFlagDefault = (flag: MenuSdkFeatureFlag): boolean =>
  MENU_SDK_FEATURE_FLAG_DEFAULTS.flags[flag];
