const fs = require('fs');
const s = 'F:/Manaintibojanam_final2/orderbhojan/scripts/post-deploy-proof-recovery-01.mjs';
const o = 'F:/Manaintibojanam_final2/orderbhojan/scripts/post-deploy-location-fix-proof.mjs';
let t = fs.readFileSync(s, 'utf8');
t = t.replaceAll('orderbhojan/post-deploy-proof-report.json', 'orderbhojan/post-deploy-location-fix-report.json');
t = t.replaceAll('orderbhojan/post-deploy-proof', 'orderbhojan/post-deploy-location-fix-proof');
t = t.replace("commit: 'fcf1a12'", "commit: '7158a2f'");
t = t.replace("bundleBefore: 'assets/index-CTeHnmoB.js'", "bundleBefore: 'assets/index-UZ7_2QNQ.js'");
t = t.replace("bundleAfter: 'assets/index-vps-IMXb.js'", "bundleAfter: 'assets/index-DoFE5dzf.js'");
fs.writeFileSync(o, t, { encoding: 'utf8' });
console.log('ok');
