/**
 * Pricing domain reason codes (M8 PR-2).
 */

export const PRICING_REASON_CODES = {
  INVALID_MONEY: 'INVALID_MONEY',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  INVALID_DECIMAL_PRECISION: 'INVALID_DECIMAL_PRECISION',
  INVALID_TAX_RATE: 'INVALID_TAX_RATE',
  INVALID_GST_RATE: 'INVALID_GST_RATE',
  INVALID_GST_CATEGORY: 'INVALID_GST_CATEGORY',
  INVALID_GST_BREAKDOWN: 'INVALID_GST_BREAKDOWN',
  INVALID_PRICE: 'INVALID_PRICE',
  INVALID_PRICE_SNAPSHOT: 'INVALID_PRICE_SNAPSHOT',
  INVALID_DISCOUNT: 'INVALID_DISCOUNT',
  INVALID_DISCOUNT_TYPE: 'INVALID_DISCOUNT_TYPE',
  INVALID_DISCOUNT_POLICY: 'INVALID_DISCOUNT_POLICY',
  INVALID_COUPON: 'INVALID_COUPON',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_USAGE_EXCEEDED: 'COUPON_USAGE_EXCEEDED',
  COUPON_INACTIVE: 'COUPON_INACTIVE',
  INVALID_CAMPAIGN: 'INVALID_CAMPAIGN',
  CAMPAIGN_INACTIVE: 'CAMPAIGN_INACTIVE',
  CAMPAIGN_OUTSIDE_WINDOW: 'CAMPAIGN_OUTSIDE_WINDOW',
  INVALID_OFFER: 'INVALID_OFFER',
  OFFER_INACTIVE: 'OFFER_INACTIVE',
  INVALID_OFFER_RULE: 'INVALID_OFFER_RULE',
  INVALID_PRICE_LIST: 'INVALID_PRICE_LIST',
  EMPTY_PRICE_LIST: 'EMPTY_PRICE_LIST',
  INVALID_BRANCH_OVERRIDE: 'INVALID_BRANCH_OVERRIDE',
  INVALID_BRANCH_PRICING: 'INVALID_BRANCH_PRICING',
  INVALID_DELIVERY_CHARGE: 'INVALID_DELIVERY_CHARGE',
  INVALID_DELIVERY_RULE: 'INVALID_DELIVERY_RULE',
  INVALID_DELIVERY_ZONE: 'INVALID_DELIVERY_ZONE',
  INVALID_PACKAGING_CHARGE: 'INVALID_PACKAGING_CHARGE',
  INVALID_PACKAGING_RULE: 'INVALID_PACKAGING_RULE',
} as const;

export type PricingReasonCode = (typeof PRICING_REASON_CODES)[keyof typeof PRICING_REASON_CODES];

export const PRICING_REASON_MESSAGES: Partial<Record<PricingReasonCode, string>> = {
  INVALID_MONEY: 'Money amount must be non-negative and finite',
  INVALID_CURRENCY: 'Currency code is required',
  INVALID_DECIMAL_PRECISION: 'Amount exceeds allowed decimal precision',
  INVALID_GST_RATE: 'GST rate must be between 0 and 100',
  INVALID_COUPON: 'Coupon code is required',
  COUPON_EXPIRED: 'Coupon has expired',
  COUPON_USAGE_EXCEEDED: 'Coupon usage limit exceeded',
  EMPTY_PRICE_LIST: 'Price list must contain at least one price',
};
