/**
 * DiscoverySDK feature flags (M3 foundation).
 * All flags default OFF — zero production impact until PR-2+.
 */

export type DiscoverySdkFeatureFlag =
  | 'FF_DISCOVERY_ENABLED'
  | 'FF_DISCOVERY_RANKING_ENABLED'
  | 'FF_DISCOVERY_MARKETPLACE_ENABLED'
  | 'FF_DISCOVERY_TENANT_REPOSITORY_ENABLED'
  | 'FF_DISCOVERY_ELIGIBILITY_ENABLED'
  | 'FF_DISCOVERY_GEOINDEX_ENABLED';

export const DISCOVERY_SDK_FEATURE_FLAG_DEFAULTS = {
  flags: {
    FF_DISCOVERY_ENABLED: false,
    FF_DISCOVERY_RANKING_ENABLED: false,
    FF_DISCOVERY_MARKETPLACE_ENABLED: false,
    FF_DISCOVERY_TENANT_REPOSITORY_ENABLED: false,
    FF_DISCOVERY_ELIGIBILITY_ENABLED: false,
    FF_DISCOVERY_GEOINDEX_ENABLED: false,
  },
} as const;

export const DISCOVERY_SDK_FEATURE_FLAG_ENV_KEYS: Record<DiscoverySdkFeatureFlag, string> = {
  FF_DISCOVERY_ENABLED: 'VITE_FF_DISCOVERY_ENABLED',
  FF_DISCOVERY_RANKING_ENABLED: 'VITE_FF_DISCOVERY_RANKING_ENABLED',
  FF_DISCOVERY_MARKETPLACE_ENABLED: 'VITE_FF_DISCOVERY_MARKETPLACE_ENABLED',
  FF_DISCOVERY_TENANT_REPOSITORY_ENABLED: 'VITE_FF_DISCOVERY_TENANT_REPOSITORY_ENABLED',
  FF_DISCOVERY_ELIGIBILITY_ENABLED: 'VITE_FF_DISCOVERY_ELIGIBILITY_ENABLED',
  FF_DISCOVERY_GEOINDEX_ENABLED: 'VITE_FF_DISCOVERY_GEOINDEX_ENABLED',
};

export type DiscoveryFeatureFlagReader = (flag: DiscoverySdkFeatureFlag) => boolean;

export const readDiscoveryFlagDefault = (flag: DiscoverySdkFeatureFlag): boolean =>
  DISCOVERY_SDK_FEATURE_FLAG_DEFAULTS.flags[flag];
